# Generated by Django 6.0.2 on 2026-02-17 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_seed_initial_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "course", "verbose_name_plural": "courses"},
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["status", "created_at"], name="courses_cou_status_ed6868_idx"
            ),
        ),
    ]
