# Generated by Django 6.0.2 on 2026-02-17 23:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_alter_course_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('passing_score', models.PositiveIntegerField(default=70, help_text='Minimum score to pass the assessment.')),
                ('total_score', models.PositiveIntegerField(default=100, help_text='Total score for the assessment.')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.course')),
                ('lesson', models.OneToOneField(blank=True, help_text='Optional: Link this assessment to a specific lesson.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment', to='courses.lesson')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
