# Generated by Django 6.0.2 on 2026-02-18 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_alter_assessment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together=set(),
        ),
    ]
