# Generated by Django 6.0.2 on 2026-02-18 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_alter_assessment_unique_together'),
        ('courses', '0004_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Optional: Link this assessment to a specific lesson.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='courses.lesson'),
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('course', 'title')},
        ),
    ]
